---
- name : Extracting files to remote server
  unarchive: 
    src: .circleci/ansible/roles/deploy/files/artifact.tar.gz
    dest: ./
    remote_src: yes

- name : Installing dependencies
  shell: |
    npm install

- name : Executing node
  shell: |
    pm2 stop default
    pm2 start npm -- start